use_frameworks!

platform :ios, '13.0'

target 'InnovationEngineService_Example' do
  pod 'InnovationEngineService', :path => '../'

  target 'InnovationEngineService_Tests' do
    inherit! :search_paths

    
  end
end
